
from .keyboard_for_message_id_193 import keyboard_for_message_id_193
from .keyboard_for_message_id_190 import keyboard_for_message_id_190
from .keyboard_for_message_id_182 import keyboard_for_message_id_182
from .keyboard_for_message_id_178 import keyboard_for_message_id_178
from .keyboard_for_message_id_150 import keyboard_for_message_id_150
from .keyboard_for_message_id_127 import keyboard_for_message_id_127